### ISSUE TITLE
The data of the Form is not returned as expected

### ISSUE THREAD

**Issue by Ayyoub-ESSADEQ** [bendera/vscode-webview-elements#100]
I was developing a form using the `vscode-form-container` , but when I tried to access the data of the form I just get a portion. The input areas declared using `vscode-textfield` do not show up, but those declared using `vscode-inputbox` do appear in the form data.

**Comment by bendera** [comment]
Which version do you use? I know this bug but it was fixed in the 0.10.3. 

Btw. I'm working on the implementation of the ElementInternals API, which means the form controls will be able to work as a native form control.

**Comment by Ayyoub-ESSADEQ** [comment]
Thanks. The problem was actually with the version `0.8.0` which I'm using.
