### ISSUE TITLE
Icons in tree

### ISSUE THREAD

**Issue by worksofliam** [bendera/vscode-webview-elements#15]
First off, awesome work & thank you for 0.3!

I am trying to build some new UI using your tree view, but mostly as a clickable list.

I have it working really well - except the icons do not show up!

Here is a screenshot of what I have:

![image](https://user-images.githubusercontent.com/3708366/118409263-8aadfb80-b657-11eb-9f47-ca53f9469097.png)

Here is how I am building my array:

```js
      {
        icons: {
          leaf: `plus`
        },
        label: `New Action`,
        value: `-1`
      },
      ...allActions.map((action, index) => ({
        icons: {
          leaf: `debug-start`
        },
        label: `${action.name} (${action.type}: ${action.extensions.join(`, `)})`,
        value: String(index)
      }))
```

I can see from the developer tools.. it looks correct:

```html
<span class="codicon codicon-debug-start" style="animation-duration: 1.5s; font-size: 16px; height: 16px; width: 16px;"></span>
```

Wondering if you had any pointers? Thanks!

**Comment by worksofliam** [comment]
I also looked up the codicon icons and tried that with no luck:

```js
      {
        icons: {
          leaf: `add`
        },
        label: `New Action`,
        value: `-1`
      },
      ...allActions.map((action, index) => ({
        icons: {
          leaf: `edit`
        },
        label: `${action.name} (${action.type}: ${action.extensions.join(`, `)})`,
        value: String(index)
      }))
```

![image](https://user-images.githubusercontent.com/3708366/118409415-4cfda280-b658-11eb-83a1-bc4833d681c2.png)

**Comment by bendera** [comment]
Hi,

Did you append this line to the header?

`<link rel="stylesheet" href="path/to/codicon.css" id="vscode-codicon-stylesheet">`

**Comment by worksofliam** [comment]
No, I don't think I did! 

Do I need to install conditions into my extension too?

**Comment by bendera** [comment]
> No, I don't think I did!

Probably that's the problem. it would be nicer if there was no need for an additional link tag but it cannot be solved any other way.

> Do I need to install codicons into my extension too?

Yes, you should install the vscode-codicons package (or copy the files manually, it's up to you). Check this demo for example:
https://github.com/bendera/vscode-vscwe-demo/blob/master/src/extension.ts

**Comment by worksofliam** [comment]
Okay, thank you @bendera. 

I didn't realise that. I'll try that and will post back here.

**Comment by worksofliam** [comment]
It's going to take some work to get codicons with webpack. I will close this for now.

Thanks @bendera!
