### ISSUE TITLE
Programmatically update vscode-single-select

### ISSUE THREAD

**Issue by nk-coding** [bendera/vscode-webview-elements#16]
Is there a way to programmatically update the selected option of a single-select (not in Combobox mode)?  
I tried setting `value` and `selectedIndex`, however this does not update `_labelText`, therefore the label is not updated  
I could change the slotted elements (as this would result in `_onSlotChange` being called), however I think this is more a hack than a solution

**Comment by bendera** [comment]
It's definitely a bug, it should work.

**Comment by bendera** [comment]
Fixed.
