### ISSUE TITLE
click event for vscode-radio in vscode-radio-group

### ISSUE THREAD

**Issue by Vi-brance** [bendera/vscode-webview-elements#59]
Hello! I found a problem while browsering `RadioGroup` [webpage](https://bendera.github.io/vscode-webview-elements/components/vscode-radio-group/). When I repeatedly click on the `Radio` of the `RadioGroup` component, it will be unchecked, and clicking again will not be selected.

I tried using the `Radio` component alone, it works correctly, so I suspect there is a problem with the logic of the `RadioGroup` component.

Thank you for your hard work and excellent package!

**Comment by bendera** [comment]
Hi, I'm glad to like it.

I managed to reproduce that bug, thank you for reporting it.
