### ISSUE TITLE
Thanks! 

### ISSUE THREAD

**Issue by worksofliam** [bendera/vscode-webview-elements#8]
Hey, no issue as such, but more of a thank you.

I have been struggling to make UI for my extension for such a long time. It was hard to support different themes... but your library just works!

Here's a simple login form I made using it (and am about to ship it).

![image](https://user-images.githubusercontent.com/3708366/109901466-22aa6480-7c67-11eb-8715-256cc4d3d4b8.png)

Also, to make it easy for my extension to add more UI I made a simple class ([see the docs here](https://github.com/halcyon-tech/code-for-ibmi/blob/master/docs/api/custom-ui.md)) so I never have to write any HTML again.

Again - thanks for the excellent work.

**Comment by bendera** [comment]
Hi,

Thank you for your feedback! :)
