### ISSUE TITLE
vscode-inputbox maxlength support

### ISSUE THREAD

**Issue by worksofliam** [bendera/vscode-webview-elements#9]
It'd be nice if the `vscode-inputbox` component could support `maxlength` property.

**Comment by bendera** [comment]
I've added a bunch of native HTML attributes. Please install the pre-release version:
`npm i @bendera/vscode-webview-elements@0.3.0-alpha.2` or `npm i @bendera/vscode-webview-elements@next`
The minified version was renamed to `bundled.js`
