### ISSUE TITLE
Is that possible add indeterminate attribute to the vscode-checkbox

### ISSUE THREAD

**Issue by BoykaZhu** [bendera/vscode-webview-elements#92]
Right now when we using vscode-checkbox, it only has checked or not status.
That will be great if there is the indeterminate attr, then it will have more chances to use this elem.

**Comment by bendera** [comment]
It's a good idea, I'll implement it soon.

**Comment by bendera** [comment]
Done.

**Comment by BoykaZhu** [comment]
The latest version works for me.
